parameters:
#    cloudlogin.example.class: Cloud\loginBundle\Example

services:
#    cloudlogin.example:
#        class: %cloudlogin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
