security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
#cloud
    firewalls:
#        login_firewall:
#            pattern:    ^/login$
#            anonymous:  ~
        fronted:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                remember_me: true
                use_referer: true
                always_use_default_target_path: true
                default_target_path: cloud_cloudspaces_homepage
            logout:
                path: /logout
                target: /login
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        login:
#            pattern:  ^/demo/secured/login$
#            security: false
#
#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: _security_check
#                login_path: _demo_login
#            logout:
#                path:   _demo_logout
#                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

#    access_control:
#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
# cloud
    access_control:
          - { path: ^/[a-z][a-z]/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/[a-z][a-z]/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/[a-z][a-z]/recover, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/[a-z][a-z]/passwordreset/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/[a-z][a-z]/admin, roles: ROLE_ADMIN }
          - { path: ^/*, roles: ROLE_USER }



        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }

    providers:
        usuarios:
            entity: { class: Cloud\UsuarioBundle\Entity\Usuarios, property: email }

    encoders:
        Cloud\UsuarioBundle\Entity\Usuarios: { algorithm: sha512, iterations: 10 }