parameters:
#    cloud_admin.example.class: Cloud\AdminBundle\Example

services:
#    cloud_admin.example:
#        class: %cloud_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
