parameters:
#    cloud_cloudspaces.example.class: Cloud\CloudspacesBundle\Example

services:
#    cloud_cloudspaces.example:
#        class: %cloud_cloudspaces.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

